# Generated by Django 4.2.13 on 2024-06-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='isPlayable',
            field=models.BooleanField(default=True),
        ),
    ]
