# Generated by Django 4.2.13 on 2024-07-18 00:13

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    admin_group, created = Group.objects.get_or_create(name='Admin')
    user_group, created = Group.objects.get_or_create(name='User')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.RunPython(create_groups),
    ]
