# Generated by Django 4.2.13 on 2024-07-18 01:19

from django.db import migrations
from django.contrib.auth.models import Group, User

def assign_admin_group(apps, schema_editor):
    admin_group, created = Group.objects.get_or_create(name='Admin')
    if created:
        print("Admin group created")
    User = apps.get_model('auth', 'User')
    try:
        user = User.objects.get(username="tempy")
        user.groups.add(admin_group.id)  # Use the group ID
    except User.DoesNotExist:
        print("User does not exist")

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_quiz'),
    ]

    operations = [
        migrations.RunPython(assign_admin_group),
    ]
